"""Exercise smoke training followed by the complete R1 evaluation CLI."""

from __future__ import annotations

import hashlib
import json
import shutil
import subprocess
import sys
from pathlib import Path
from tempfile import TemporaryDirectory

import yaml

REPOSITORY_ROOT = Path(__file__).resolve().parents[2]
WORKSPACE_DIRECTORIES = ("config", "datasets", "evaluation", "helix", "research")


def _copy_workspace(workspace: Path) -> None:
    for filename in ("train.py", "evaluate.py"):
        shutil.copy2(REPOSITORY_ROOT / filename, workspace / filename)
    for directory in WORKSPACE_DIRECTORIES:
        shutil.copytree(
            REPOSITORY_ROOT / directory,
            workspace / directory,
            ignore=shutil.ignore_patterns("__pycache__", "*.pyc"),
        )


def _run(workspace: Path, *arguments: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [sys.executable, *arguments],
        cwd=workspace,
        capture_output=True,
        text=True,
        timeout=180,
        check=False,
    )


def _assert_succeeded(result: subprocess.CompletedProcess[str]) -> None:
    message = (
        f"subprocess exited with {result.returncode}"
        f"\nstdout:\n{result.stdout}"
        f"\nstderr:\n{result.stderr}"
    )
    assert result.returncode == 0, message


def _write_raw_manifest(
    workspace: Path,
    *,
    manifest_name: str,
    dataset_id: str,
    version: str,
    text_path: Path,
) -> Path:
    content = text_path.read_bytes()
    relative_text_path = text_path.relative_to(workspace).as_posix()
    manifest_path = workspace / "evaluation/datasets/manifests" / manifest_name
    manifest = {
        "dataset_id": dataset_id,
        "display_name": f"{dataset_id} integration fixture",
        "current_version": version,
        "canonical_source": {
            "url": "https://example.invalid/integration-fixture.txt",
            "selection_rationale": "Synthetic integration fixture only.",
            "retrieved_at": "2026-07-20T00:00:00Z",
            "retrieval_method": "Generated by the integration test.",
        },
        "raw": {
            "expected_path": relative_text_path,
            "encoding": "utf-8",
            "version": version,
            "sha256": hashlib.sha256(content).hexdigest(),
            "gitignored": True,
        },
        "license": "Synthetic integration fixture.",
        "processed": [],
        "fallback_sources": [],
    }
    manifest_path.write_text(json.dumps(manifest), encoding="utf-8")
    return manifest_path


def _write_evaluation_fixtures(workspace: Path) -> Path:
    raw_directory = workspace / "evaluation/datasets/raw/integration"
    raw_directory.mkdir(parents=True, exist_ok=True)
    in_corpus_path = raw_directory / "moby.txt"
    in_corpus_path.write_text(
        "Call me Ishmael. The ship crossed the sea while the captain watched the mast.\n",
        encoding="utf-8",
    )
    out_of_corpus_path = raw_directory / "alice.txt"
    out_of_corpus_path.write_text(
        "Alice followed a white rabbit through a quiet garden and found a curious door.\n",
        encoding="utf-8",
    )
    in_manifest = _write_raw_manifest(
        workspace,
        manifest_name="integration-moby.json",
        dataset_id="integration-moby-dick",
        version="fixture-v1",
        text_path=in_corpus_path,
    )
    out_manifest = _write_raw_manifest(
        workspace,
        manifest_name="integration-alice.json",
        dataset_id="integration-alice",
        version="fixture-v1",
        text_path=out_of_corpus_path,
    )

    prompt_path = workspace / "evaluation/prompts/fixed_suite_v1.json"
    prompt_suite = json.loads(prompt_path.read_text(encoding="utf-8"))
    assert isinstance(prompt_suite, dict)
    prompt_suite["max_new_tokens"] = 2
    prompt_path.write_text(json.dumps(prompt_suite), encoding="utf-8")

    config = {
        "datasets": {
            "in_corpus": {
                "manifest_path": in_manifest.relative_to(workspace).as_posix(),
                "text_path": in_corpus_path.relative_to(workspace).as_posix(),
                "artifact": "raw",
            },
            "out_of_corpus": {
                "manifest_path": out_manifest.relative_to(workspace).as_posix(),
                "text_path": out_of_corpus_path.relative_to(workspace).as_posix(),
                "artifact": "raw",
            },
            "memorization_corpus": {
                "manifest_path": in_manifest.relative_to(workspace).as_posix(),
                "text_path": in_corpus_path.relative_to(workspace).as_posix(),
                "artifact": "raw",
            },
        },
        "prompts": {"path": "evaluation/prompts/fixed_suite_v1.json"},
        "metrics": {
            "repetition_n": 4,
            "distinct_n": 2,
            "min_memorization_overlap_tokens": 4,
        },
        "rubric": {
            "id": "helix-qualitative-rubric",
            "version": "v1",
            "path": "evaluation/rubric/qualitative_rubric_v1.md",
        },
        "reports": {"directory": "evaluation/reports"},
    }
    config_path = workspace / "evaluation/integration.yaml"
    config_path.write_text(yaml.safe_dump(config, sort_keys=False), encoding="utf-8")
    return config_path


def test_smoke_checkpoint_produces_complete_evaluation_report() -> None:
    with TemporaryDirectory(prefix="helix-evaluate-smoke-") as temporary_directory:
        workspace = Path(temporary_directory) / "helix"
        workspace.mkdir()
        _copy_workspace(workspace)
        config_path = _write_evaluation_fixtures(workspace)

        training_result = _run(
            workspace,
            "train.py",
            "--config",
            "config/training/smoke.yaml",
        )
        _assert_succeeded(training_result)
        checkpoint_path = workspace / "checkpoints/smoke/latest.pt"
        assert checkpoint_path.is_file()

        evaluation_result = _run(
            workspace,
            "evaluate.py",
            "--checkpoint",
            "checkpoints/smoke/latest.pt",
            "--config",
            config_path.relative_to(workspace).as_posix(),
        )
        _assert_succeeded(evaluation_result)

        report_path = Path(evaluation_result.stdout.strip().splitlines()[-1])
        assert report_path.is_file()
        assert report_path.parent.parent.resolve() == (workspace / "evaluation/reports").resolve()
        report = report_path.read_text(encoding="utf-8")
        assert "# Helix Evaluation Report" in report
        assert "integration-moby-dick" in report
        assert "integration-alice" in report
        assert "## Perplexity" in report
        assert "## Automated Generation Metrics" in report
        assert "## Memorization Findings" in report
        assert "## Prompt And Completion Pairs" in report
        assert "## Qualitative Scores (Manual)" in report
        assert "| Grammaticality |  |  |" in report
        for prompt_id in (
            "moby-opening-reflection",
            "whaling-voyage",
            "captain-at-sea",
            "harpooner-description",
            "white-whale-rumor",
            "nineteenth-century-storm",
            "garden-story",
            "tea-instructions",
            "leaves-explanation",
            "train-arithmetic",
            "friendly-letter",
            "market-scene",
        ):
            assert prompt_id in report
